### ISSUE TITLE
Transplier Conflict with VFE 

### ISSUE THREAD

**Issue by TheLoneTec** [PeteTimesSix/ResearchReinvented#17]
Both patch the same method. I tried placing before VFE but that caused occasional unity crashes.

the patch is "Frame_CompleteConstruction_Patch" (named the same)

"RR: Frame_CompleteConstruction_Patches - TranspilerForQuality - failed to apply patch (instructions not found)"

**Comment by Toby222** [comment]
Which mod, specifically?

**Comment by TheLoneTec** [comment]
VFECore in Vanilla Expanded Framework
