### ISSUE TITLE
Frequent Freezing

### ISSUE THREAD

**Issue by Sixdd6** [PeteTimesSix/ResearchReinvented#2]
I'm experiencing frequent freezing for up to 20-30 seconds whenever any pawn is doing generic research at a research bench. From what I've seen so far the game runs without issue when I draft my researcher pawns and let the game run but when I undraft them the game will freeze again the moment one of them becomes assigned to researching at the bench. This occurred when researching vanilla Autodoors.

[Huglib log](https://gist.github.com/382a9754c43d834560b4b94413d69f91)

**Comment by Sixdd6** [comment]
After a bit of further testing it seems to not be related to the research bench. Using WorkTab I disabled the vanilla "do research" work type and upon unpausing the game it immediately froze. Completely disabling all work types under Research job and unpausing did allow the game to continue running normally. Then re-enabling the Research job and unpausing did again cause the game to freeze.

**Comment by Sixdd6** [comment]
The following is another log immediately after a freeze, if more is needed I'll be happy to help further.
[Hugslib log](https://gist.github.com/87f6cd3c4b949a0eaa54b874ce1dbf97)

**Comment by PeteTimesSix** [comment]
Ive made some performance improvements since, but if its still an issue see if you can profile which function is causing the slowdown with Dubs' Performance Analyzer.

**Comment by Sixdd6** [comment]
Everything seems to be better now, I've played for a few hours now and didn't have a single freezeup so I think we can close this.
